### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by soundstep** [alexpovel/ancv#225]
Hi there, I found this project really fun!

However, it was working but it is not working anymore:

```sh
curl -L ancv.io/soundstep
```

<img width="456" alt="Screenshot 2024-08-27 at 14 30 00" src="https://github.com/user-attachments/assets/c1dc4981-7ae6-4662-9435-a41cc0292307">

The gist is there:
https://gist.github.com/soundstep/745bf8e9e1d2bfa7610104be96a2975c

I tried to get ancv with pip and that command does work:

```sh
ancv render resume.json
```

Any idea?

**Comment by alexpovel** [comment]
Hi! Thanks a lot for the feedback and report. It was just an expired token. I implemented health checks now, so this should be caught in the future.

Check it out, it should work again!

**Comment by soundstep** [comment]
@alexpovel Awesome, thanks for the quick fix! Love it ;)
